{{- if .Values.envData -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "as400rpc.envSecretName" . }}
data:
{{ range $key, $value := .Values.envData }}
   {{ $key }}: {{ $value | b64enc | quote }}
{{ end }}
{{- end -}}
