# permissions for end users to view as400rpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: as400rpc-viewer-role
rules:
- apiGroups:
  - openlegacy.com
  resources:
  - as400rpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openlegacy.com
  resources:
  - as400rpcs/status
  verbs:
  - get
