# permissions for end users to edit as400rpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: as400rpc-editor-role
rules:
- apiGroups:
  - openlegacy.com
  resources:
  - as400rpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openlegacy.com
  resources:
  - as400rpcs/status
  verbs:
  - get
