# permissions for end users to edit as400-rpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: as400-rpc-editor-role
rules:
- apiGroups:
  - openlegacy.com
  resources:
  - as400-rpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openlegacy.com
  resources:
  - as400-rpcs/status
  verbs:
  - get
