apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: as400rpc-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: no-code application that allows simple configuration-based integration to AS/400 systems.
  displayName: as400rpc-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Integration
  links:
  - name: As400rpc Operator
    url: https://as400rpc-operator.domain
  maintainers:
  - email: sergiy.n@openlegacy.com
    name: SergeN
  maturity: alpha
  provider:
    name: Openlegacy
    url: https://www.openlegacy.com
  version: 0.0.0
