apiVersion: v1
kind: Service
metadata:
  name: {{ include "as400-rpc.fullname" . }}
  labels:
    {{- include "as400-rpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: app
  selector:
    component: {{ include "as400-rpc.fullname" . }}
    {{- include "as400-rpc.selectorLabels" . | nindent 4 }}
